/* eslint-disable @next/next/no-img-element */
"use client";
import { FormEvent, useMemo, useState } from "react";
import { BookOpenText, Camera, Film, Heart, MoreHorizontal, Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { WorkspaceOverlay } from "@/components/trip/WorkspaceOverlay";
import { uploadMediaFile } from "@/components/media/client-upload";
import type { KnowledgeEntryView } from "@/services/knowledge-service.server";

const sections = { photography: { label: "拍照知识", icon: Camera }, transition_video: { label: "转场视频", icon: Film }, travel_guide: { label: "旅游攻略", icon: BookOpenText } } as const;
const blank = { section: "photography", title: "", summary: "", body: "", destination: "", externalUrl: "", tags: "", mediaAssetIds: [] as string[] };
export function KnowledgeLibraryClient({ entries, initialSection = "", favoriteOnly = false }: { entries: KnowledgeEntryView[]; initialSection?: string; favoriteOnly?: boolean }) {
  const router = useRouter(); const [open, setOpen] = useState(false), [editing, setEditing] = useState<KnowledgeEntryView | null>(null), [form, setForm] = useState(blank), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const tags = useMemo(() => [...new Set(entries.flatMap((entry) => entry.tags))], [entries]);
  function start(entry?: KnowledgeEntryView) { setEditing(entry || null); setForm(entry ? { section: entry.section, title: entry.title, summary: entry.summary || "", body: entry.body || "", destination: entry.destination || "", externalUrl: entry.externalUrl || "", tags: entry.tags.join("，"), mediaAssetIds: entry.mediaAssetIds } : { ...blank, section: initialSection && initialSection in sections ? initialSection : "photography" }); setError(""); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(editing ? `/api/knowledge/${editing.id}` : "/api/knowledge", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, tags: form.tags.split(/[，,]/).map((tag) => tag.trim()).filter(Boolean) }) }); const payload = await response.json() as { message?: string }; if (!response.ok) throw new Error(payload.message || "保存失败。"); setOpen(false); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存失败。"); } finally { setSaving(false); } }
  async function upload(files: FileList | null) { if (!files?.length) return; setSaving(true); try { const ids: string[] = []; for (const file of [...files].slice(0, 12 - form.mediaAssetIds.length)) ids.push(await uploadMediaFile(file, "knowledge_image")); setForm((current) => ({ ...current, mediaAssetIds: [...current.mediaAssetIds, ...ids] })); } catch (caught) { setError(caught instanceof Error ? caught.message : "图片上传失败。"); } finally { setSaving(false); } }
  async function favorite(entry: KnowledgeEntryView) { await fetch(`/api/knowledge/${entry.id}/favorite`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ favorite: !entry.favorite }) }); router.refresh(); }
  async function remove(entry: KnowledgeEntryView) { if (!confirm(`确定删除“${entry.title}”吗？`)) return; await fetch(`/api/knowledge/${entry.id}`, { method: "DELETE" }); router.refresh(); }
  return <>
    <div className="knowledge-toolbar"><nav><Link className={!initialSection && !favoriteOnly ? "active" : ""} href="/knowledge">全部</Link>{Object.entries(sections).map(([key, value]) => <Link className={initialSection === key ? "active" : ""} key={key} href={`/knowledge?section=${key}`}>{value.label}</Link>)}<Link className={favoriteOnly ? "active" : ""} href="/knowledge?favorite=1">收藏</Link></nav>{tags.length ? <div className="knowledge-tag-row">{tags.map((tag) => <Link key={tag} href={`/knowledge?tag=${encodeURIComponent(tag)}`}>#{tag}</Link>)}</div> : null}</div>
    <button type="button" className="global-floating-add knowledge-floating-add" aria-label="添加知识" onClick={() => start()}><Plus size={30} /></button>
    {!entries.length ? <section className="knowledge-empty"><BookOpenText size={62} /><h2>暂无内容</h2><button type="button" onClick={() => start()}>添加知识</button></section> : <section className="knowledge-grid">{entries.map((entry) => { const meta = sections[entry.section]; const Icon = meta.icon; const mediaCover = entry.coverMediaAssetId || entry.mediaAssetIds[0]; const coverSrc = mediaCover ? `/api/media/${mediaCover}?variant=card` : entry.coverImageUrl; return <article className="knowledge-card" key={entry.id}>{coverSrc ? <Link href={`/knowledge/${entry.id}`} className="knowledge-card-cover"><img src={coverSrc} alt="" loading="lazy" /></Link> : <Link href={`/knowledge/${entry.id}`} className="knowledge-card-cover empty"><Icon size={42} /></Link>}<div className="knowledge-card-body"><span><Icon size={15} />{meta.label}</span><Link href={`/knowledge/${entry.id}`}><h2>{entry.title}</h2></Link>{entry.summary && <p>{entry.summary}</p>}<div className="knowledge-card-meta">{entry.destination && <small>{entry.destination}</small>}{entry.tags.map((tag) => <small key={tag}>#{tag}</small>)}</div></div><div className="knowledge-card-actions"><button type="button" aria-label={entry.favorite ? "取消收藏" : "收藏"} onClick={() => favorite(entry)}><Heart size={18} fill={entry.favorite ? "currentColor" : "none"} /></button><button type="button" aria-label="编辑知识" onClick={() => start(entry)}><MoreHorizontal size={18} /></button><button type="button" onClick={() => remove(entry)}>删除</button></div></article>; })}</section>}
    <WorkspaceOverlay open={open} onClose={() => !saving && setOpen(false)} ariaLabel={editing ? "编辑知识" : "添加知识"} className="knowledge-editor clean-dialog"><header className="editor-dialog-heading"><h2>{editing ? "编辑知识" : "添加知识"}</h2><button type="button" aria-label="关闭" onClick={() => setOpen(false)}><X size={20} /></button></header><form onSubmit={submit}><label>栏目<select value={form.section} onChange={(e) => setForm({ ...form, section: e.target.value })}>{Object.entries(sections).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select></label><label>标题<input required maxLength={120} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>简短说明<input maxLength={500} value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} /></label><label>正文<textarea rows={7} maxLength={12000} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /></label><div className="knowledge-editor-row"><label>目的地<input maxLength={100} value={form.destination} onChange={(e) => setForm({ ...form, destination: e.target.value })} /></label><label>标签<input placeholder="人像，夜景" value={form.tags} onChange={(e) => setForm({ ...form, tags: e.target.value })} /></label></div><label>外部链接<input type="url" placeholder="https://" value={form.externalUrl} onChange={(e) => setForm({ ...form, externalUrl: e.target.value })} /></label>{form.mediaAssetIds.length ? <div className="knowledge-editor-images">{form.mediaAssetIds.map((id) => <div key={id}><img src={`/api/media/${id}?variant=thumbnail`} alt="" /><button type="button" aria-label="移除图片" onClick={() => setForm((current) => ({ ...current, mediaAssetIds: current.mediaAssetIds.filter((item) => item !== id) }))}><X size={15} /></button></div>)}</div> : null}<label className="knowledge-upload">图片<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={(e) => upload(e.target.files)} /><span>{form.mediaAssetIds.length ? `继续添加（已有 ${form.mediaAssetIds.length} 张）` : "选择图片"}</span></label>{error && <p role="alert" className="form-error">{error}</p>}<footer><button type="button" onClick={() => setOpen(false)}>取消</button><button type="submit" disabled={saving}>{saving ? "保存中…" : "保存"}</button></footer></form></WorkspaceOverlay>
  </>;
}

