"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { Camera, X } from "lucide-react";
import { buildIdentitySwitchReturnTo } from "@/services/identity-navigation";
import { uploadMediaFile } from "@/components/media/client-upload";
export type SessionMemberSummary = { id: string; displayName: string; avatar?: string | null };
function currentPath() { return typeof window === "undefined" ? "/" : `${window.location.pathname}${window.location.search}${window.location.hash}`; }
export function MemberIdentityControl({ currentMember, compact = false }: { currentMember?: SessionMemberSummary | null; compact?: boolean }) {
  const [member, setMember] = useState(currentMember), [open, setOpen] = useState(false), [busy, setBusy] = useState<"avatar" | "switch" | "logout" | null>(null), [error, setError] = useState("");
  const triggerRef = useRef<HTMLButtonElement>(null), inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!open) return; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", escape); const old = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", escape); document.body.style.overflow = old; }; }, [open]);
  if (!member) return null;
  function close() { setOpen(false); setError(""); window.setTimeout(() => triggerRef.current?.focus(), 0); }
  async function uploadAvatar(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setBusy("avatar"); setError(""); try { const assetId = await uploadMediaFile(file, "member_avatar"); const response = await fetch("/api/member", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ assetId }) }); const payload = await response.json() as { member?: SessionMemberSummary; error?: string }; if (!response.ok || !payload.member) throw new Error(payload.error || "头像更新失败。"); setMember(payload.member); window.dispatchEvent(new CustomEvent("member-avatar-updated", { detail: payload.member })); } catch (caught) { setError(caught instanceof Error ? caught.message : "头像更新失败。"); } finally { setBusy(null); } }
  async function clearSession(destination: "switch" | "logout") { setBusy(destination); setError(""); try { const response = await fetch("/api/session", { method: "DELETE", credentials: "same-origin" }); if (!response.ok) throw new Error("操作失败，请重试。"); const returnTo = destination === "switch" ? buildIdentitySwitchReturnTo(currentPath()) : "/"; window.location.assign(`/unlock?returnTo=${encodeURIComponent(returnTo)}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "操作失败，请重试。"); setBusy(null); } }
  return <div className={`member-identity-control${compact ? " member-identity-compact" : ""}`}><button ref={triggerRef} type="button" className="member-identity-trigger" aria-haspopup="dialog" aria-expanded={open} onClick={() => setOpen(true)}>{member.avatar ? <img src={member.avatar} alt="" width={36} height={36} /> : <i aria-hidden="true">{member.displayName.slice(0, 1).toUpperCase()}</i>}<strong>{member.displayName}</strong><span aria-hidden="true">⌄</span></button>
    {open && <div className="member-profile-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) close(); }}><section className="member-profile-dialog" role="dialog" aria-modal="true" aria-label="个人资料"><header><h2>个人资料</h2><button type="button" aria-label="关闭" onClick={close} disabled={!!busy}><X size={20} /></button></header><div className="member-profile-avatar">{member.avatar ? <img src={member.avatar} alt={`${member.displayName}的头像`} /> : <i>{member.displayName.slice(0, 1).toUpperCase()}</i>}<button type="button" onClick={() => inputRef.current?.click()} disabled={!!busy}><Camera size={17} />{busy === "avatar" ? "上传中…" : "更换头像"}</button><input ref={inputRef} type="file" hidden accept="image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif" onChange={uploadAvatar} /></div><label className="member-profile-name"><span>名字</span><input readOnly value={member.displayName} /></label>{error && <p className="member-identity-error" role="alert">{error}</p>}<footer><button type="button" onClick={() => void clearSession("switch")} disabled={!!busy}>切换身份</button><button type="button" className="member-identity-logout" onClick={() => void clearSession("logout")} disabled={!!busy}>退出</button></footer></section></div>}
  </div>;
}
