/* eslint-disable @next/next/no-img-element */
"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, ImagePlus, Star, Trash2 } from "lucide-react";
import { uploadMediaFile } from "./client-upload";

type Photo = { assetId: string; filename: string; sortOrder: number };
type Album = { id: string; title: string; description: string | null; tripId: string | null; tripTitle: string | null; createdByMemberId: string; coverMediaAssetId: string | null; photos: Photo[]; canEditAlbum: boolean };
type TripOption = { id: string; title: string };
export function AlbumDetailClient({ album, trips }: { album: Album; trips: TripOption[] }) {
  const router = useRouter();
  const [title, setTitle] = useState(album.title), [description, setDescription] = useState(album.description || ""), [tripId, setTripId] = useState(album.tripId || ""), [busy, setBusy] = useState(""), [error, setError] = useState("");
  async function json(url: string, init: RequestInit) { const response = await fetch(url, init); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "操作失败，请重试。"); return payload; }
  async function save(event: FormEvent) { event.preventDefault(); setBusy("save"); setError(""); try { await json(`/api/albums/${album.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, description, tripId: tripId || null }) }); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存失败。"); } finally { setBusy(""); } }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const files = [...(event.target.files || [])]; event.target.value = ""; if (!files.length) return; if (files.length > 20) { setError("每次最多上传 20 张照片。"); return; } setBusy("upload"); setError(""); try { const ids: string[] = []; for (const file of files) ids.push(await uploadMediaFile(file, "album")); await json(`/api/albums/${album.id}/media`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ assetIds: ids }) }); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "照片上传失败。"); } finally { setBusy(""); } }
  async function reorder(index: number, direction: -1 | 1) { const next = [...album.photos], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setBusy("order"); try { await json(`/api/albums/${album.id}/media`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ assetIds: next.map((photo) => photo.assetId) }) }); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "排序失败。"); } finally { setBusy(""); } }
  async function cover(assetId: string) { setBusy(assetId); try { await json(`/api/albums/${album.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ coverMediaAssetId: assetId }) }); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "封面设置失败。"); } finally { setBusy(""); } }
  async function remove(assetId: string) { if (!window.confirm("确定永久删除这张照片吗？")) return; setBusy(assetId); try { await json(`/api/albums/${album.id}/media/${assetId}`, { method: "DELETE" }); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "删除失败。"); } finally { setBusy(""); } }
  async function removeAlbum() { if (!window.confirm("确定删除这个相册吗？相册会被隐藏，照片仍会保留。")) return; setBusy("delete"); try { await json(`/api/albums/${album.id}`, { method: "DELETE" }); router.push("/albums"); } catch (caught) { setError(caught instanceof Error ? caught.message : "删除失败。"); } finally { setBusy(""); } }
  return <>
    {album.canEditAlbum && <form className="album-form album-edit-form" onSubmit={save}><label>标题<input required maxLength={80} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>关联旅行<select value={tripId} onChange={(event) => setTripId(event.target.value)}><option value="">不关联旅行 · 全员共同相册</option>{trips.map((trip) => <option key={trip.id} value={trip.id}>{trip.title}</option>)}</select></label><label>简介<textarea maxLength={500} rows={2} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div><button type="submit" disabled={Boolean(busy)}>{busy === "save" ? "保存中…" : "保存信息"}</button><button className="danger" type="button" disabled={Boolean(busy)} onClick={removeAlbum}>删除相册</button></div></form>}
    <div className="album-upload"><label className={busy ? "disabled" : ""}><ImagePlus size={20} />{busy === "upload" ? "上传中…" : "上传照片（最多20张）"}<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif" multiple disabled={Boolean(busy)} onChange={upload} /></label></div>
    {error && <p className="form-error album-error" role="alert">{error}</p>}
    {!album.photos.length ? <section className="album-photo-empty"><ImagePlus size={50} /><p>还没有照片，放入第一张旅行记忆吧。</p></section> : <div className="album-photo-grid">{album.photos.map((photo, index) => <figure key={photo.assetId}><img src={`/api/media/${photo.assetId}?variant=card`} alt={photo.filename} width={720} height={540} loading={index < 4 ? "eager" : "lazy"} /><figcaption><span>{index + 1}</span><button title="上移" disabled={Boolean(busy) || index === 0} onClick={() => reorder(index, -1)}><ArrowUp size={16} /></button><button title="下移" disabled={Boolean(busy) || index === album.photos.length - 1} onClick={() => reorder(index, 1)}><ArrowDown size={16} /></button><button title="设为封面" className={album.coverMediaAssetId === photo.assetId ? "active" : ""} disabled={Boolean(busy)} onClick={() => cover(photo.assetId)}><Star size={16} /></button><button title="删除照片" disabled={Boolean(busy)} onClick={() => remove(photo.assetId)}><Trash2 size={16} /></button></figcaption></figure>)}</div>}
  </>;
}
