"use client";

import { useEffect, useState } from "react";

type City = { id: string; name: string };
type Place = { id: string; name: string; address: string | null; cityId: string; latitude: number | null; longitude: number | null; providerPlaceId?: string | null };
type Poi = { id: string; name: string; address: string | null; district: string | null; longitude: number; latitude: number };

/** Bind an existing formal Item to a real AMap Place without creating another
 * itinerary item.  The item remains the source of its day/order semantics. */
export function ItineraryItemPlaceControl({ slug, itemId, cities, currentPlace, defaultCityId }: { slug: string; itemId: string; cities: City[]; currentPlace: Place | null; defaultCityId?: string }) {
  const [open, setOpen] = useState(false), [cityId, setCityId] = useState(defaultCityId || cities[0]?.id || ""), [keywords, setKeywords] = useState(currentPlace?.name || ""), [results, setResults] = useState<Poi[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (!open || !keywords.trim() || !cityId) return; const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/amap/places/search?keywords=${encodeURIComponent(keywords.trim())}&cityId=${encodeURIComponent(cityId)}&tripSlug=${encodeURIComponent(slug)}`, { signal: controller.signal }); const payload = await response.json() as { pois?: Poi[]; error?: string }; if (!response.ok) throw new Error(payload.error || "地点搜索失败"); setResults(payload.pois || []); } catch (caught) { if (!controller.signal.aborted) setError(caught instanceof Error ? caught.message : "地点搜索失败"); } finally { if (!controller.signal.aborted) setLoading(false); } }, 280); return () => { controller.abort(); window.clearTimeout(timer); }; }, [cityId, keywords, open, slug]);
  async function bind(providerPlaceId: string) { setLoading(true); setError(""); try { const placeResponse = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/places`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ providerPlaceId, cityId }) }); const placePayload = await placeResponse.json() as { place?: Place; error?: string }; if (!placeResponse.ok || !placePayload.place) throw new Error(placePayload.error || "地点保存失败"); const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/items/${encodeURIComponent(itemId)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ placeId: placePayload.place.id }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "行程地点绑定失败"); location.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : "行程地点绑定失败"); setLoading(false); } }
  return <details className="item-place-control" open={open} onToggle={(event) => { const nextOpen = (event.currentTarget as HTMLDetailsElement).open; setOpen(nextOpen); if (!nextOpen) setResults([]); }}><summary>{currentPlace ? "修改地点" : "完善地点"}</summary><div><label>城市<select value={cityId} onChange={(event) => { setCityId(event.target.value); setResults([]); }}>{cities.map((city) => <option value={city.id} key={city.id}>{city.name}</option>)}</select></label><label>搜索地点<input value={keywords} onChange={(event) => { setKeywords(event.target.value); setResults([]); }} placeholder="灵隐寺、西湖、财神庙…" /></label>{loading && <small>搜索中…</small>}{results.length > 0 && <ul>{results.map((poi) => <li key={poi.id}><span><b>{poi.name}</b><small>{[poi.district, poi.address].filter(Boolean).join(" · ") || "暂无地址"}</small></span><button type="button" onClick={() => void bind(poi.id)} disabled={loading}>绑定</button></li>)}</ul>}{error && <small className="form-error" role="alert">{error}</small>}<small>绑定后会保留当前 Day、顺序和参与成员，只更新这一条事项的 Place。</small></div></details>;
}
