"use client";
import { useEffect, useState } from "react";
import { BookOpenText, Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { WorkspaceOverlay } from "./WorkspaceOverlay";
type Entry = { id: string; title: string; summary: string | null; destination: string | null; tags: string[]; legacyRecommendationId: string | null };
export function KnowledgeTripPicker({ slug, days, defaultDayId }: { slug: string; days: { id: string; label: string }[]; defaultDayId: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false), [entries, setEntries] = useState<Entry[]>([]), [query, setQuery] = useState(""), [dayId, setDayId] = useState(defaultDayId), [saving, setSaving] = useState(""), [error, setError] = useState("");
  useEffect(() => { if (!open) return; fetch("/api/knowledge?section=travel_guide").then((r) => r.json()).then((data: { entries?: Entry[] }) => setEntries(data.entries || [])).catch(() => setError("知识库读取失败。")); }, [open]);
  const visible = entries.filter((entry) => !query || `${entry.title}${entry.summary || ""}${entry.destination || ""}${entry.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  async function add(entry: Entry) { setSaving(entry.id); setError(""); try { const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/knowledge-items`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entryId: entry.id, dayId }) }); const payload = await response.json() as { message?: string; error?: string }; if (!response.ok) throw new Error(payload.message || payload.error || "添加失败。"); setOpen(false); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "添加失败。"); } finally { setSaving(""); } }
  return <><button className="knowledge-picker-trigger" type="button" onClick={() => setOpen(true)}><BookOpenText size={19} />从知识库添加</button><WorkspaceOverlay open={open} onClose={() => !saving && setOpen(false)} ariaLabel="从知识库添加" className="knowledge-picker-dialog clean-dialog"><header className="editor-dialog-heading"><h2>从知识库添加</h2><button type="button" aria-label="关闭" onClick={() => setOpen(false)}><X size={20} /></button></header><div className="knowledge-picker-filters"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索攻略、目的地或标签" /><select value={dayId} onChange={(e) => setDayId(e.target.value)}>{days.map((day) => <option key={day.id} value={day.id}>{day.label}</option>)}</select></div><div className="knowledge-picker-list">{visible.map((entry) => <article key={entry.id}><div><b>{entry.title}</b><p>{entry.destination || entry.summary || "旅游攻略"}</p><small>{entry.tags.map((tag) => `#${tag}`).join(" ")}</small></div><button type="button" disabled={Boolean(saving)} onClick={() => add(entry)}><Plus size={17} />{saving === entry.id ? "添加中" : "添加"}</button></article>)}{!visible.length && <p className="plan-empty">知识库中暂无匹配攻略。</p>}</div>{error && <p className="form-error" role="alert">{error}</p>}</WorkspaceOverlay></>;
}
