/* eslint-disable react-hooks/set-state-in-effect, jsx-a11y/no-autofocus, jsx-a11y/label-has-associated-control */
"use client";
import { useEffect, useState } from "react";

type DayOption = { id: string; label: string };
type CityOption = { id: string; name: string };
type Poi = { id: string; name: string; address: string | null; district: string | null; longitude: number; latitude: number };

export function PlanAddControl({ slug, days, cities, defaultDayId }: { slug: string; days: DayOption[]; cities: CityOption[]; defaultDayId: string }) {
  const [open, setOpen] = useState(false), [kind, setKind] = useState<"place" | "note">("place"), [dayId, setDayId] = useState(defaultDayId), [cityId, setCityId] = useState(cities[0]?.id || ""), [keywords, setKeywords] = useState(""), [pois, setPois] = useState<Poi[]>([]), [selectedPoi, setSelectedPoi] = useState(""), [title, setTitle] = useState(""), [note, setNote] = useState(""), [loading, setLoading] = useState(false), [searching, setSearching] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (!open || kind !== "place" || !keywords.trim() || !cityId) { setPois([]); return; } const timer = window.setTimeout(async () => { setSearching(true); try { const response = await fetch(`/api/amap/places/search?keywords=${encodeURIComponent(keywords.trim())}&cityId=${encodeURIComponent(cityId)}&tripSlug=${encodeURIComponent(slug)}`); const payload = await response.json() as { pois?: Poi[]; error?: string }; if (!response.ok) throw new Error(payload.error || "搜索失败"); setPois(payload.pois || []); } catch (caught) { setError(caught instanceof Error ? caught.message : "搜索失败"); } finally { setSearching(false); } }, 320); return () => window.clearTimeout(timer); }, [open, kind, keywords, cityId, slug]);
  async function submit() { setLoading(true); setError(""); try { const body = kind === "place" ? { dayId, providerPlaceId: selectedPoi, cityId, itemType: "place" } : { dayId, title: title.trim(), note: note.trim() || null, itemType: "note" }; if (kind === "place" && !selectedPoi) throw new Error("请先选择一个高德地点"); if (kind === "note" && !title.trim()) throw new Error("请填写事项名称"); const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/items`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "添加失败"); setOpen(false); setKeywords(""); setPois([]); setSelectedPoi(""); setTitle(""); setNote(""); location.assign(`/trips/${encodeURIComponent(slug)}/plan?view=planning&day=${encodeURIComponent(dayId)}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "添加失败"); setLoading(false); } }
  return <>
    <button type="button" className="add-itinerary-button" onClick={() => { setDayId(defaultDayId); setOpen(true); }}>＋ 添加行程</button>
    {open && <div className="plan-add-modal" role="dialog" aria-modal="true" aria-label="添加行程"><div className="plan-add-sheet"><header><div><span>ADD TO DAY</span><h3>把什么放进行程？</h3></div><button type="button" aria-label="关闭" onClick={() => setOpen(false)}>×</button></header><label>目标日期<select value={dayId} onChange={(event) => setDayId(event.target.value)}>{days.map((day) => <option key={day.id} value={day.id}>{day.label}</option>)}</select></label><div className="plan-add-kind"><button type="button" className={kind === "place" ? "active" : ""} onClick={() => setKind("place")}>搜索地点</button><button type="button" className={kind === "note" ? "active" : ""} onClick={() => setKind("note")}>添加普通事项</button></div>{kind === "place" ? <div className="plan-add-search"><label>城市<select value={cityId} onChange={(event) => { setCityId(event.target.value); setSelectedPoi(""); }}>{cities.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</select></label><label>搜索地点<input autoFocus value={keywords} onChange={(event) => { setKeywords(event.target.value); setSelectedPoi(""); }} placeholder="静安寺、餐厅、酒店、龙翔桥…" /></label>{searching && <small>搜索中…</small>}{pois.length > 0 && <div className="plan-add-pois" role="radiogroup" aria-label="地点搜索结果">{pois.map((poi) => <label key={poi.id} className={selectedPoi === poi.id ? "selected" : ""}><input type="radio" name="plan-add-poi" checked={selectedPoi === poi.id} onChange={() => setSelectedPoi(poi.id)} /><span><b>{poi.name}</b><small>{[poi.district, poi.address].filter(Boolean).join(" · ") || "暂无地址"}</small></span></label>)}</div>}</div> : <div className="plan-add-note"><label>事项名称<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="集合、休息、取行李、自由活动…" /></label><label>备注（可选）<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label></div>}{error && <p className="form-error" role="alert">{error}</p>}<button type="button" className="plan-add-submit" disabled={loading} onClick={submit}>{loading ? "保存中…" : "加入这一天"}</button></div></div>}
  </>;
}
