/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-autofocus */
"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import type { AMapRouteMode, AMapRouteResult } from "@/services/amap/amap-types";

type Place = { id: string; name: string; cityId: string; address: string | null; latitude: number | null; longitude: number | null; district?: string | null; providerPlaceId?: string | null };
type Day = { id: string; dayNumber: number; date: string | null; title: string; items: { item: { id: string; title: string; dayId: string; sortOrder: number; lockedAt: string | null; placeId: string | null }; place: Place | null }[] };
type Stop = { id: string; source: "itinerary" | "booking"; title: string; place: Place; sortOrder: number; memberStates?: Record<string, "present" | "absent" | "unknown"> };
type Segment = { id: string; from: Stop; to: Stop; crossCity: boolean };
type MapEntry = { place: Place; kind: "itinerary" | "booking" | "recommendation" | "saved" | "candidate"; planStatus: "candidate" | "selected" | "locked"; category?: string | null; areaKey?: string | null; recommendationTitle?: string | null };
type Workspace = { days: Day[]; cities: { id: string; name: string }[]; members?: { id: string; displayName: string }[]; currentMemberId?: string | null; bookings?: { id: string; title: string; type: string; placeId?: string | null }[]; mapPlaces?: MapEntry[]; savedPlaces?: { id: string; place: Place; note?: string | null }[]; routeStopsByDay?: Record<string, Stop[]>; routeSegmentsByDay?: Record<string, Segment[]>; routePreferences?: { dayId: string; fromId: string; toId: string; memberId: string | null; preferredMode: AMapRouteMode }[] };

type AMapObject = { add(value: unknown): void; remove(value: unknown): void; setFitView(value?: unknown[]): void; setCenter?(value: [number, number]): void; getBounds?(): { getSouthWest?: () => { lng: number; lat: number }; getNorthEast?: () => { lng: number; lat: number } }; on?(event: string, handler: (event?: unknown) => void): void; destroy(): void };
type AMapMarker = { on?(event: string, handler: () => void): void };
type AMapNamespace = { Map: new (container: HTMLDivElement, options: Record<string, unknown>) => AMapObject; Marker: new (options: Record<string, unknown>) => AMapMarker; Polyline: new (options: Record<string, unknown>) => unknown };
declare global { interface Window { AMap?: AMapNamespace; _AMapSecurityConfig?: { serviceHost: string } } }

let loader: Promise<AMapNamespace> | null = null;
async function loadAMap() {
  if (window.AMap) return window.AMap;
  if (!loader) loader = (async () => {
    const response = await fetch("/api/amap/config"), config = await response.json() as { key?: string; version?: string; serviceHost?: string; error?: string };
    if (!response.ok || !config.key || !config.serviceHost) throw new Error(config.error || "地图配置读取失败。");
    window._AMapSecurityConfig = { serviceHost: config.serviceHost };
    await new Promise<void>((resolve, reject) => {
      const existing = document.querySelector<HTMLScriptElement>("script[data-trip-amap]");
      if (existing) { if (window.AMap) resolve(); else { existing.addEventListener("load", () => resolve(), { once: true }); existing.addEventListener("error", () => reject(new Error("高德地图加载失败。")), { once: true }); } return; }
      const script = document.createElement("script"); script.dataset.tripAmap = "true"; script.src = `https://webapi.amap.com/maps?v=${encodeURIComponent(config.version || "2.0")}&key=${encodeURIComponent(config.key)}`; script.async = true; script.onload = () => resolve(); script.onerror = () => reject(new Error("高德地图加载失败。")); document.head.appendChild(script);
    });
    if (!window.AMap) throw new Error("高德地图加载失败。"); return window.AMap;
  })();
  return loader;
}

const modeLabels: Record<AMapRouteMode, string> = { walking: "步行", subway: "地铁", bus: "公交", mixed_transit: "地铁 + 公交", taxi: "打车", driving: "驾车", bicycling: "骑行", transit: "公共交通" };
const categoryLabels = [{ key: "all", label: "全部" }, { key: "attraction", label: "景点" }, { key: "food", label: "美食" }, { key: "cafe", label: "咖啡" }, { key: "shopping", label: "购物" }, { key: "guide", label: "攻略" }, { key: "other", label: "其他" }];
function minutes(seconds: number | null) { return seconds == null ? "时间待确认" : `${Math.max(1, Math.round(seconds / 60))} 分钟`; }
function distance(meters: number | null) { return meters == null ? "距离待确认" : meters < 1000 ? `${Math.round(meters)} 米` : `${(meters / 1000).toFixed(1)} 公里`; }
function shortDate(date: string | null) { return date ? date.slice(5).replace("-", "/") : "日期未定"; }
function placeArea(place: Place, cities: { id: string; name: string }[]) { const city = cities.find((item) => item.id === place.cityId)?.name || ""; return (place.name.includes("桐庐") || place.district?.includes("桐庐")) ? "tonglu" : city.includes("上海") ? "shanghai" : "hangzhou"; }
function placeCategory(entry: MapEntry) { if (entry.category === "hotel" || entry.category === "experience") return "other"; return entry.category || (entry.kind === "recommendation" ? "attraction" : "other"); }

export function PlanMap({ slug, places = [], workspace, activeDayId, mapMode = "day" }: { slug: string; places?: { id: string; name: string; latitude: number | null; longitude: number | null; candidate: boolean; order: number | null }[]; workspace?: Workspace; activeDayId?: string; mapMode?: "day" | "library" }) {
  const container = useRef<HTMLDivElement>(null), mapRef = useRef<AMapObject | null>(null), overlays = useRef<unknown[]>([]);
  const defaultRouteKey = useRef("");
  const [ready, setReady] = useState(false), [error, setError] = useState(""), [search, setSearch] = useState(""), [searching, setSearching] = useState(false), [searchResults, setSearchResults] = useState<{ id: string; name: string; address: string | null; district: string | null; longitude: number; latitude: number }[]>([]), [selectedSearch, setSelectedSearch] = useState<string | null>(null), [selectedMapEntryId, setSelectedMapEntryId] = useState<string | null>(null), [bindingBookingId, setBindingBookingId] = useState(""), [area, setArea] = useState("all"), [category, setCategory] = useState("all"), [dayFilter, setDayFilter] = useState("all"), [memberFilter, setMemberFilter] = useState("all"), [targetDayId, setTargetDayId] = useState(activeDayId || ""), [routeResults, setRouteResults] = useState<Record<string, AMapRouteResult>>({}), [routeComparisons, setRouteComparisons] = useState<Record<string, Partial<Record<AMapRouteMode, AMapRouteResult>>>>({}), [routing, setRouting] = useState<string | null>(null), [selectedRoute, setSelectedRoute] = useState<string | null>(null), [viewport, setViewport] = useState<{ south: number; west: number; north: number; east: number } | null>(null), [manualPoint, setManualPoint] = useState<{ longitude: number; latitude: number } | null>(null), [manualName, setManualName] = useState(""), [manualAddress, setManualAddress] = useState(""), [manualBookingId, setManualBookingId] = useState("");
  const activeDay = workspace?.days.find((day) => day.id === activeDayId) || workspace?.days[0];
  const allDayStops = activeDay && workspace?.routeStopsByDay?.[activeDay.id] ? workspace.routeStopsByDay[activeDay.id] : [];
  const dayStops = memberFilter === "all" ? allDayStops : allDayStops.filter((stop) => stop.memberStates?.[memberFilter] !== "absent");
  const daySegments = dayStops.slice(1).map((to, index) => { const from = dayStops[index]; return { id: `${from.id}-${to.id}`, from, to, crossCity: from.place.cityId !== to.place.cityId }; });
  const entries = useMemo<MapEntry[]>(() => workspace?.mapPlaces || places.map((place) => ({ place: { ...place, cityId: "" }, kind: place.candidate ? "candidate" : "itinerary", planStatus: place.candidate ? "candidate" : "selected" })), [workspace, places]);
  const mapEntries = useMemo(() => {
    if (!workspace || mapMode === "day") {
      const order = new Map(dayStops.map((stop, index) => [stop.place.id, index]));
      return entries.filter((entry) => !workspace || order.has(entry.place.id)).sort((a, b) => (order.get(a.place.id) ?? 9999) - (order.get(b.place.id) ?? 9999) || a.place.id.localeCompare(b.place.id));
    }
    // A Day filter is a visual highlight, not a hard hide.  The library map is
    // an all-trip spatial overview; non-matching places remain visible but are
    // deliberately muted by the marker layer below.
    return entries.filter((entry) => (area === "all" || placeArea(entry.place, workspace.cities) === area) && (category === "all" || placeCategory(entry) === category));
  }, [area, category, dayFilter, dayStops, entries, mapMode, workspace]);
  const visible = mapEntries.filter((entry) => entry.place.latitude != null && entry.place.longitude != null);
  const dayHighlightIds = useMemo(() => new Set((workspace?.days.find((day) => day.id === dayFilter)?.items || []).map(({ item }) => item.placeId).filter((id): id is string => Boolean(id))), [dayFilter, workspace]);
  // Tonglu is an area/region under Hangzhou, not a separate Trip City.  Keep
  // the persisted city relation on Hangzhou while using 桐庐 only as the
  // provider search region.
  const searchCity = workspace?.cities.find((item) => (area === "hangzhou" || area === "tonglu") && item.name.includes("杭州")) || workspace?.cities.find((item) => area === "shanghai" && item.name.includes("上海")) || workspace?.cities.find((item) => item.name.includes("上海")) || workspace?.cities[0];
  const searchRegion = area === "tonglu" ? "桐庐" : searchCity?.name || "";
  useEffect(() => { let cancelled = false; loadAMap().then((AMap) => { if (cancelled || !container.current) return; mapRef.current = new AMap.Map(container.current, { zoom: 11, center: [121.47, 31.23], viewMode: "2D" }); setReady(true); }).catch((caught) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "地图加载失败。"); }); return () => { cancelled = true; mapRef.current?.destroy(); mapRef.current = null; }; }, []);
  useEffect(() => { if (!ready || !mapRef.current?.on) return; const map = mapRef.current; const updateViewport = () => { const bounds = map.getBounds?.(), sw = bounds?.getSouthWest?.(), ne = bounds?.getNorthEast?.(); if (sw && ne) setViewport({ south: sw.lat, west: sw.lng, north: ne.lat, east: ne.lng }); }; map.on("moveend", updateViewport); map.on("zoomend", updateViewport); updateViewport(); }, [ready]);
  useEffect(() => { if (!ready || !mapRef.current?.on) return; mapRef.current.on("click", (event) => { const lnglat = (event as { lnglat?: { lng?: number; lat?: number; getLng?: () => number; getLat?: () => number } } | undefined)?.lnglat; const longitude = lnglat?.lng ?? lnglat?.getLng?.(), latitude = lnglat?.lat ?? lnglat?.getLat?.(); if (longitude != null && latitude != null && Number.isFinite(longitude) && Number.isFinite(latitude)) setManualPoint({ longitude, latitude }); }); }, [ready]);
  useEffect(() => { const map = mapRef.current, AMap = window.AMap; if (!ready || !map || !AMap) return; if (overlays.current.length) map.remove(overlays.current); const itineraryNumbers = new Map(mapEntries.filter((entry) => entry.kind === "itinerary").map((entry, index) => [entry.place.id, index + 1])); const markers = visible.map((entry) => { const markerNumber = mapMode === "day" ? itineraryNumbers.get(entry.place.id) : null; const baseOpacity = entry.kind === "candidate" ? .28 : entry.kind === "saved" ? .58 : entry.kind === "recommendation" ? .78 : 1; const mutedByDay = mapMode === "library" && dayFilter !== "all" && !dayHighlightIds.has(entry.place.id) ? .38 : 1; const marker = new AMap.Marker({ position: [entry.place.longitude!, entry.place.latitude!], title: entry.place.name, opacity: baseOpacity * mutedByDay, label: { content: markerNumber ? `${markerNumber}. ${entry.place.name}` : entry.kind === "booking" ? `⚑ ${entry.place.name}` : entry.place.name, direction: "top" } }); marker.on?.("click", () => { setSelectedMapEntryId(entry.place.id); setSelectedSearch(null); }); return marker; }); const lines = Object.values(routeResults).flatMap((route) => (route.polylines || []).map((path) => new AMap.Polyline({ path, strokeColor: "#bf6648", strokeWeight: 5, strokeOpacity: .88, showDir: true }))); const resultMarkers = searchResults.map((poi) => { const marker = new AMap.Marker({ position: [poi.longitude, poi.latitude], title: poi.name, opacity: selectedSearch === poi.id ? 1 : .72, label: { content: `⌖ ${poi.name}`, direction: "top" } }); marker.on?.("click", () => { setSelectedSearch(poi.id); setSelectedMapEntryId(null); }); return marker; }); overlays.current = [...markers, ...lines, ...resultMarkers]; if (overlays.current.length) map.add(overlays.current); if (visible.length) map.setFitView(markers); }, [dayFilter, dayHighlightIds, mapEntries, mapMode, ready, routeResults, searchResults, selectedSearch, visible]);
  useEffect(() => { if (!ready || !mapRef.current?.setCenter || !searchResults.length) return; const poi = searchResults.find((item) => item.id === selectedSearch) || searchResults[0]; mapRef.current.setCenter?.([poi.longitude, poi.latitude]); }, [ready, searchResults, selectedSearch]);
  useEffect(() => { if (!workspace || mapMode !== "day") return; setRouteResults({}); setRouteComparisons({}); setSelectedRoute(null); setTargetDayId(activeDayId || workspace.days[0]?.id || ""); }, [activeDayId, mapMode, memberFilter, workspace]);
  useEffect(() => { if (!search.trim() || !searchCity) { setSearchResults([]); return; } const timer = window.setTimeout(async () => { setSearching(true); setError(""); try { const params = new URLSearchParams({ keywords: search.trim(), cityId: searchCity.id, tripSlug: slug }); if (searchRegion) params.set("region", searchRegion); const response = await fetch(`/api/amap/places/search?${params}`); const payload = await response.json() as { pois?: typeof searchResults; error?: string }; if (!response.ok) throw new Error(payload.error || "搜索失败"); setSearchResults(payload.pois || []); } catch (caught) { setError(caught instanceof Error ? caught.message : "搜索失败"); } finally { setSearching(false); } }, 320); return () => window.clearTimeout(timer); }, [search, searchCity, searchRegion, slug]);
  function preferredFor(segment: Segment) { return workspace?.routePreferences?.find((preference) => preference.dayId === activeDay?.id && preference.fromId === segment.from.id && preference.toId === segment.to.id && (preference.memberId === memberFilter || (memberFilter === "all" && preference.memberId === (workspace.currentMemberId || null))))?.preferredMode || "subway"; }
  async function planSegment(segment: Segment, mode: AMapRouteMode, persistPreference = true) { const cached = routeComparisons[segment.id]?.[mode]; if (cached) { setRouteResults((current) => ({ ...current, [segment.id]: cached })); setSelectedRoute(segment.id); if (!persistPreference) return; } setRouting(segment.id); setError(""); try { let route = cached; if (!route) { const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/routes`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ originPlaceId: segment.from.place.id, destinationPlaceId: segment.to.place.id, mode }) }); const payload = await response.json() as { route?: AMapRouteResult; error?: string }; if (!response.ok || !payload.route) throw new Error(payload.error || "路线规划失败"); route = payload.route; setRouteResults((current) => ({ ...current, [segment.id]: route! })); setRouteComparisons((current) => ({ ...current, [segment.id]: { ...(current[segment.id] || {}), [mode]: route! } })); setSelectedRoute(segment.id); } if (persistPreference) { const preference = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/preferences`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ dayId: activeDay?.id, fromSource: segment.from.source, fromId: segment.from.id, toSource: segment.to.source, toId: segment.to.id, preferredMode: mode }) }); if (!preference.ok) setError("路线已显示，但交通偏好暂未保存。"); } } catch (caught) { setError(caught instanceof Error ? caught.message : "路线规划失败"); } finally { setRouting(null); } }
  useEffect(() => { if (mapMode !== "day" || !activeDay || !daySegments.length) return; const first = daySegments.find((segment) => !segment.crossCity); if (!first || defaultRouteKey.current === `${activeDay.id}:${first.id}` || routeResults[first.id] || routing) return; defaultRouteKey.current = `${activeDay.id}:${first.id}`; void planSegment(first, preferredFor(first), false); }, [activeDay, daySegments, mapMode, routeResults, routing]);
  async function saveSearch(action: "add" | "save" | "recommendation") { const poi = searchResults.find((item) => item.id === selectedSearch); if (!poi || !searchCity) return; setSearching(true); try { const endpoint = action === "add" ? `/api/trips/${encodeURIComponent(slug)}/plan/items` : action === "save" ? `/api/trips/${encodeURIComponent(slug)}/saved-places` : `/api/trips/${encodeURIComponent(slug)}/recommendations`; const body = action === "add" ? { dayId: targetDayId || activeDay?.id, providerPlaceId: poi.id, cityId: searchCity.id, itemType: "place" } : action === "save" ? { providerPlaceId: poi.id, cityId: searchCity.id } : { title: poi.name, providerPlaceId: poi.id, cityId: searchCity.id, category: "attraction", areaKey: area === "tonglu" ? "tonglu" : area === "hangzhou" ? "hangzhou" : area === "shanghai" ? "shanghai" : null, areaLabel: area === "tonglu" ? "桐庐" : searchCity.name }; const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "保存失败"); location.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : "保存失败"); } finally { setSearching(false); } }
  async function bindSearchToBooking() {
    const poi = searchResults.find((item) => item.id === selectedSearch);
    if (!poi || !searchCity || !bindingBookingId) return;
    setSearching(true); setError("");
    try {
      const placeResponse = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/places`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ providerPlaceId: poi.id, cityId: searchCity.id }) });
      const placePayload = await placeResponse.json() as { place?: { id: string }; error?: string };
      if (!placeResponse.ok || !placePayload.place) throw new Error(placePayload.error || "地点保存失败");
      const bookingResponse = await fetch(`/api/trips/${encodeURIComponent(slug)}/budget/bookings/${encodeURIComponent(bindingBookingId)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ placeId: placePayload.place.id }) });
      const bookingPayload = await bookingResponse.json() as { error?: string };
      if (!bookingResponse.ok) throw new Error(bookingPayload.error || "订单绑定失败");
      location.reload();
    } catch (caught) { setError(caught instanceof Error ? caught.message : "订单绑定失败"); setSearching(false); }
  }
  async function saveMapEntry(action: "add" | "save" | "recommendation") {
    const entry = entries.find((candidate) => candidate.place.id === selectedMapEntryId);
    if (!entry || !workspace) return;
    if (action === "add" && entry.kind === "booking") return;
    setSearching(true); setError("");
    try {
      const endpoint = action === "add" ? `/api/trips/${encodeURIComponent(slug)}/plan/items` : action === "save" ? `/api/trips/${encodeURIComponent(slug)}/saved-places` : `/api/trips/${encodeURIComponent(slug)}/recommendations`;
      const body = action === "add" ? { dayId: targetDayId || activeDay?.id, placeId: entry.place.id, itemType: "place" } : action === "save" ? { placeId: entry.place.id } : { title: entry.recommendationTitle || entry.place.name, placeId: entry.place.id, category: entry.category && ["attraction", "food", "cafe", "shopping", "hotel", "experience", "other"].includes(entry.category) ? entry.category : "attraction" };
      const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      const payload = await response.json() as { error?: string };
      if (!response.ok) throw new Error(payload.error || "保存失败");
      location.reload();
    } catch (caught) { setError(caught instanceof Error ? caught.message : "保存失败"); setSearching(false); }
  }
  async function saveSavedAsRecommendation(saved: NonNullable<Workspace["savedPlaces"]>[number]) {
    setSearching(true); setError("");
    try {
      const savedArea = saved.city.name.includes("杭州") ? "hangzhou" : saved.city.name.includes("上海") ? "shanghai" : null;
      const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/recommendations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: saved.place.name, placeId: saved.place.id, category: "attraction", areaKey: savedArea, areaLabel: saved.city.name, summary: saved.note || saved.place.address || null }) });
      const payload = await response.json() as { error?: string };
      if (!response.ok) throw new Error(payload.error || "收藏攻略失败");
      location.reload();
    } catch (caught) { setError(caught instanceof Error ? caught.message : "收藏攻略失败"); setSearching(false); }
  }
  async function searchThisArea() { if (!workspace || !searchCity) return; setSearching(true); setError(""); try { const params = new URLSearchParams({ keywords: search.trim() || (area === "tonglu" ? "桐庐 景点" : "景点"), cityId: searchCity.id, tripSlug: slug }); if (searchRegion) params.set("region", searchRegion); if (viewport) params.set("rectangle", `${viewport.west},${viewport.south};${viewport.east},${viewport.north}`); const response = await fetch(`/api/amap/places/search?${params}`); const payload = await response.json() as { pois?: typeof searchResults; error?: string }; if (!response.ok) throw new Error(payload.error || "区域搜索失败"); setSearchResults(payload.pois || []); setSelectedSearch(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "区域搜索失败"); } finally { setSearching(false); } }
  async function createManualPoint() { if (!manualPoint || !manualName.trim() || !searchCity || !workspace) return; setSearching(true); setError(""); try { const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/places`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: manualName.trim(), address: manualAddress.trim() || null, cityId: searchCity.id, longitude: manualPoint.longitude, latitude: manualPoint.latitude }) }); const payload = await response.json() as { place?: { id: string }; error?: string }; if (!response.ok || !payload.place) throw new Error(payload.error || "手动地点保存失败"); if (manualBookingId) { const bookingResponse = await fetch(`/api/trips/${encodeURIComponent(slug)}/budget/bookings/${encodeURIComponent(manualBookingId)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ placeId: payload.place.id }) }); if (!bookingResponse.ok) { const bookingPayload = await bookingResponse.json() as { error?: string }; throw new Error(bookingPayload.error || "订单绑定失败"); } } setManualPoint(null); setManualName(""); setManualAddress(""); setManualBookingId(""); location.reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : "手动地点保存失败"); setSearching(false); } }
  return <div className={`plan-map-surface ${mapMode === "library" ? "library-map" : "route-map"}`}>
    {workspace && <div className="map-filter-bar"><div className="map-search"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索地点、餐厅、酒店…" aria-label="地图搜索地点"/><button type="button" onClick={() => setSearch(search.trim())} disabled={searching}>{searching ? "搜索中…" : "搜索"}</button></div><div className="map-target-day"><label>加入目标 Day<select value={targetDayId || activeDay?.id || ""} onChange={(event) => setTargetDayId(event.target.value)}>{workspace.days.map((day) => <option key={day.id} value={day.id}>{shortDate(day.date)} · {day.title}</option>)}</select></label>{mapMode === "library" && <button type="button" onClick={searchThisArea} disabled={searching}>{searching ? "搜索中…" : "搜索此区域"}</button>}<button type="button" onClick={() => setError("请点击地图上的准确位置来创建手动地点。")}>在地图上选点</button></div>{mapMode === "library" && <><div className="map-filter-row"><span>地域</span>{[{ key: "all", label: "全部" }, { key: "shanghai", label: "上海" }, { key: "hangzhou", label: "杭州" }, { key: "tonglu", label: "桐庐" }].map((item) => <button type="button" className={area === item.key ? "active" : ""} key={item.key} onClick={() => setArea(item.key)}>{item.label}</button>)}</div><div className="map-filter-row"><span>分类</span>{categoryLabels.map((item) => <button type="button" className={category === item.key ? "active" : ""} key={item.key} onClick={() => setCategory(item.key)}>{item.label}</button>)}</div><div className="map-filter-row"><span>Day</span><button type="button" className={dayFilter === "all" ? "active" : ""} onClick={() => setDayFilter("all")}>全部</button>{workspace.days.map((day) => <button type="button" className={dayFilter === day.id ? "active" : ""} key={day.id} onClick={() => setDayFilter(day.id)}>{shortDate(day.date)}</button>)}</div></>}{mapMode === "day" && <div className="map-filter-row"><span>路线成员</span><button type="button" className={memberFilter === "all" ? "active" : ""} onClick={() => setMemberFilter("all")}>全体</button>{(workspace.members || []).map((member) => <button type="button" className={memberFilter === member.id ? "active" : ""} key={member.id} onClick={() => setMemberFilter(member.id)}>{member.displayName}</button>)}</div>}</div>}
    {searchResults.length > 0 && <div className="map-search-results"><b>搜索结果 · 选择后可加入或暂存</b>{searchResults.map((poi) => <article key={poi.id} className={selectedSearch === poi.id ? "selected" : ""} onClick={() => setSelectedSearch(poi.id)}><div><strong>{poi.name}</strong><small>{[poi.district, poi.address].filter(Boolean).join(" · ") || "暂无地址"}</small></div>{selectedSearch === poi.id && <div className="map-search-actions"><button type="button" onClick={() => saveSearch("add")} disabled={!targetDayId}>加入 {shortDate((workspace?.days.find((day) => day.id === targetDayId) || activeDay)?.date || null)}</button><button type="button" onClick={() => saveSearch("save")}>暂存</button><button type="button" onClick={() => saveSearch("recommendation")}>收藏攻略</button>{workspace?.bookings?.length ? <div className="map-binding-actions"><select aria-label="选择要绑定的订单" value={bindingBookingId} onChange={(event) => setBindingBookingId(event.target.value)}><option value="">绑定到订单…</option>{workspace.bookings.map((booking) => <option key={booking.id} value={booking.id}>{booking.title}</option>)}</select><button type="button" onClick={bindSearchToBooking} disabled={!bindingBookingId}>确认绑定地点</button></div> : null}</div>}</article>)}</div>}
    {selectedMapEntryId && mapMode === "library" && (() => { const entry = entries.find((candidate) => candidate.place.id === selectedMapEntryId); if (!entry) return null; const canAdd = entry.kind !== "booking"; return <section className="map-entry-actions"><div><b>{entry.place.name}</b><small>{entry.place.address || "已在旅行地点库中"}</small></div><div><button type="button" onClick={() => saveMapEntry("add")} disabled={!canAdd || !targetDayId}>{canAdd ? `加入 ${shortDate((workspace?.days.find((day) => day.id === targetDayId) || activeDay)?.date || null)}` : "Booking 地点"}</button>{entry.kind !== "saved" && <button type="button" onClick={() => saveMapEntry("save")}>暂存</button>}{entry.kind !== "recommendation" && <button type="button" onClick={() => saveMapEntry("recommendation")}>收藏攻略</button>}<button type="button" className="map-entry-dismiss" onClick={() => setSelectedMapEntryId(null)}>关闭</button></div></section>; })()}
    {manualPoint && workspace && <div className="map-manual-point" role="dialog" aria-label="手动地图选点"><b>手动地点 · {manualPoint.longitude.toFixed(5)}, {manualPoint.latitude.toFixed(5)}</b><label>名称<input value={manualName} onChange={(event) => setManualName(event.target.value)} placeholder="例如：集合点" autoFocus /></label><label>地址或备注<input value={manualAddress} onChange={(event) => setManualAddress(event.target.value)} placeholder="可选" /></label>{workspace.bookings?.length ? <label>同时绑定订单（可选）<select value={manualBookingId} onChange={(event) => setManualBookingId(event.target.value)}><option value="">不绑定订单</option>{workspace.bookings.map((booking) => <option key={booking.id} value={booking.id}>{booking.title}</option>)}</select></label> : null}<div><button type="button" onClick={createManualPoint} disabled={searching || !manualName.trim()}>保存地点</button><button type="button" onClick={() => setManualPoint(null)}>取消</button></div></div>}
    {mapMode === "library" && workspace?.savedPlaces?.length ? <section className="saved-place-list"><header><b>暂存地点</b><small>不属于正式行程，选择后再加入目标 Day</small></header>{workspace.savedPlaces.map((saved) => <article key={saved.id}><div><strong>{saved.place.name}</strong><small>{saved.place.address || saved.note || "暂存地点"}</small></div><div><button type="button" onClick={async () => { const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/plan/items`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ dayId: targetDayId || activeDay?.id, placeId: saved.place.id, itemType: "place" }) }); if (response.ok) location.reload(); }}>加入 Day</button><button type="button" onClick={() => saveSavedAsRecommendation(saved)} disabled={searching}>收藏攻略</button><button type="button" onClick={async () => { const response = await fetch(`/api/trips/${encodeURIComponent(slug)}/saved-places?id=${encodeURIComponent(saved.id)}`, { method: "DELETE" }); if (response.ok) location.reload(); }}>删除</button></div></article>)}</section> : null}
    {mapMode === "day" && workspace && <section className="route-directory"><header><div><span>ROUTE</span><h3>{activeDay ? `${shortDate(activeDay.date)} · 下一站怎么走` : "当天路线"}</h3></div><small>默认只查推荐方案，点击比较再加载其他方式{memberFilter !== "all" && dayStops.some((stop) => stop.memberStates?.[memberFilter] === "unknown") ? " · 参与成员待确认" : ""}</small></header>{dayStops.length < 2 && <p className="map-empty">这一天至少需要两个带坐标的地点，才可以生成路线段。</p>}{daySegments.map((segment, index) => { const route = routeResults[segment.id], mode = route?.mode || preferredFor(segment), alternatives = routeComparisons[segment.id] || {}; return <article className="route-segment-card" key={segment.id}><div className="route-segment-head"><b>{index + 1}. {segment.from.title}</b><span>→</span><b>{segment.to.title}</b></div>{segment.crossCity ? <p className="cross-city-note">跨城市 Anchor：不绘制普通市内路线，请在订单/行程中确认长途交通。</p> : <><div className="route-choice"><span>↓ {modeLabels[mode]}{route ? ` · ${minutes(route.durationSeconds)} · ${distance(route.distanceMeters)}` : " · 推荐方案"}</span><button type="button" onClick={() => planSegment(segment, mode, false)} disabled={routing === segment.id}>{routing === segment.id ? "查询中…" : "详情"}</button><details><summary>比较</summary><div className="route-compare-buttons">{(["subway", "bus", "mixed_transit", "taxi", "walking"] as AMapRouteMode[]).map((value) => <button type="button" key={value} onClick={() => planSegment(segment, value)} disabled={routing === segment.id}>{modeLabels[value]}</button>)}</div></details></div>{route && <div className="route-detail"><span>{modeLabels[route.mode]}</span><span>{distance(route.distanceMeters)}</span><span>{minutes(route.durationSeconds)}</span>{route.transitCost != null ? <span>票价约 ¥{route.transitCost}/人</span> : route.mode === "walking" ? <span>票价 ¥0</span> : route.mode === "taxi" ? <span>车费待确认</span> : <span>票价待确认</span>}{route.taxiCost != null && <span>约 ¥{route.taxiCost}/车</span>}<button type="button" onClick={() => setSelectedRoute(selectedRoute === segment.id ? null : segment.id)}>完整步骤</button></div>}{Object.keys(alternatives).length > 1 && <div className="route-alternatives">{Object.entries(alternatives).map(([alternativeMode, alternative]) => <button type="button" key={alternativeMode} className={alternativeMode === mode ? "active" : ""} onClick={() => void planSegment(segment, alternativeMode as AMapRouteMode)}><b>{modeLabels[alternativeMode as AMapRouteMode]}</b><small>{minutes(alternative.durationSeconds)} · {distance(alternative.distanceMeters)}</small></button>)}</div>}{selectedRoute === segment.id && route?.steps?.length ? <ol className="route-steps">{route.steps.map((step, stepIndex) => <li key={`${segment.id}-${stepIndex}`}><b>{modeLabels[step.mode === "other" ? "walking" : step.mode]}</b><span>{step.lineName || step.instruction || "路线步骤"}</span>{step.direction && <small>{step.direction}</small>}{step.stationCount != null && <small>{step.stationCount} 站</small>}</li>)}</ol> : null}</>}</article>; })}</section>}
    <div className="plan-map-canvas-wrap"><div ref={container} className="plan-map-canvas" aria-label="高德地图" />{!ready && !error && <p>地图加载中…</p>}{ready && !visible.length && <p>当前视图还没有带坐标的地点。</p>}</div>
    {mapMode === "library" && <p className="map-hint">攻略地图默认展示整趟旅行的地点分布。正式行程、Booking、攻略素材、暂存地点和候选点会用不同透明度区分（候选点为淡色 Marker）；拖动后点击“搜索此区域”才会请求候选 POI。</p>}
    {error && <p className="form-error" role="alert">{error}</p>}
  </div>;
}
