/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages */
import { PlanningPanels } from "./PlanningPanels";
import { RecommendationAddControl } from "./RecommendationAddControl";
import { PlanMap } from "./PlanMap";
import { ItineraryItemControl } from "./ItineraryItemControl";
import type { getPlanWorkspace } from "@/services/plan-workspace-service.server";

type Workspace = NonNullable<Awaited<ReturnType<typeof getPlanWorkspace>>>;
type View = "planning" | "map" | "budget";
type MapMode = "day" | "library";
type AreaFilter = "shanghai" | "hangzhou" | "tonglu";
type CategoryFilter = "all" | "attraction" | "food" | "cafe" | "shopping" | "guide" | "other";

const categoryLabels = { attraction: "景点", food: "美食", cafe: "咖啡", shopping: "购物", hotel: "酒店", experience: "体验", other: "其他" } as const;
const areaFilters: { key: AreaFilter; label: string }[] = [{ key: "shanghai", label: "上海" }, { key: "hangzhou", label: "杭州" }, { key: "tonglu", label: "桐庐" }];
const categoryFilters: { key: CategoryFilter; label: string }[] = [{ key: "all", label: "全部" }, { key: "attraction", label: "景点" }, { key: "food", label: "美食" }, { key: "cafe", label: "咖啡" }, { key: "shopping", label: "购物" }, { key: "guide", label: "攻略" }, { key: "other", label: "其他" }];
function money(value: number | null | undefined) { return value == null ? "—" : `¥${(value / 100).toFixed(2).replace(/\.00$/, "")}`; }
function shortDate(date: string | null) { return date ? date.slice(5).replace("-", "/") : "日期未定"; }
function fullRange(start: string | null, end: string | null) { if (!start || !end) return "日期未定"; return `${start.replaceAll("-", ".")} — ${end.slice(5).replaceAll("-", ".")}`; }
function dayArea(day: Workspace["days"][number]) { if (day.title.includes("桐庐")) return "桐庐"; if (day.title.includes("前往杭州") || day.items.some(({ item }) => item.itemType === "transit")) return "上海→杭州"; if (day.title.includes("杭州")) return "杭州"; if (day.title.includes("上海") || day.title.includes("浦东")) return "上海"; return day.title; }
function bookingIcon(type: string) { return type === "flight" ? "✈" : type === "hotel" ? "🏨" : type === "train" ? "🚄" : "◆"; }
function bookingStatus(type: string) { return type === "flight" ? "已购" : "已订"; }
function bookingTime(booking: Workspace["bookings"][number]["booking"]) { if (booking.startAt && booking.endAt && booking.timezone) { const format = (value: string) => new Intl.DateTimeFormat("zh-CN", { timeZone: booking.timezone!, hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); return `${format(booking.startAt)}–${format(booking.endAt)}`; } return `${shortDate(booking.startDateLocal)}–${shortDate(booking.endDateLocal)}`; }

export function TripPlanWorkspace({ workspace, activeDayId, view, mapMode, query, areaFilter, categoryFilter }: { workspace: Workspace; activeDayId: string; view: View; mapMode: MapMode; query: string; areaFilter: AreaFilter; categoryFilter: CategoryFilter }) {
  const { trip, days, recommendations, bookings, costLines } = workspace;
  const activeDay = days.find((day) => day.id === activeDayId) || days[0];
  const dayLabels = days.map((day) => ({ id: day.id, label: `${shortDate(day.date)} ${dayArea(day)}` }));
  const stageSummary = trip.stages?.length ? trip.stages.map((stage) => `${stage.city?.name || stage.title}${stage.members?.length || 0}人`).join(" · ") : `${trip.members?.length || trip.people}人参与`;
  const filteredRecommendations = recommendations.filter((recommendation) => {
    const categoryMatches = categoryFilter === "all" || categoryFilter === "guide" ? categoryFilter === "all" || recommendation.kind === "guide" : categoryFilter === "other" ? recommendation.kind !== "guide" && ["other", "hotel", "experience"].includes(recommendation.category) : recommendation.kind !== "guide" && recommendation.category === categoryFilter;
    return recommendation.areaKey === areaFilter && categoryMatches && (!query || recommendation.title.toLowerCase().includes(query.toLowerCase()));
  });
  const confirmedTotal = bookings.reduce((sum, { booking }) => sum + (booking.totalAmountMinor || 0), 0);
  const itineraryPlaces = activeDay ? activeDay.items.filter(({ place }) => place).map(({ item, place }) => ({ id: place!.id, name: place!.name, latitude: place!.latitude, longitude: place!.longitude, candidate: false, order: item.sortOrder })) : [];
  const bookingPlaces = bookings.filter(({ booking, place }) => place && (booking.startDateLocal === activeDay?.date || booking.endDateLocal === activeDay?.date)).map(({ place }) => ({ id: place!.id, name: place!.name, latitude: place!.latitude, longitude: place!.longitude, candidate: false, order: null }));
  const candidatePlaces = recommendations.flatMap((recommendation) => recommendation.options.map(({ place }) => ({ id: place.id, name: place.name, latitude: place.latitude, longitude: place.longitude, candidate: true, order: null })));
  const mapPlaces = Array.from(new Map((mapMode === "library" ? [...itineraryPlaces, ...bookingPlaces, ...candidatePlaces] : [...itineraryPlaces, ...bookingPlaces]).map((place) => [place.id, place])).values());
  const link = (nextView: View, dayId = activeDayId, mode = mapMode) => { const params = new URLSearchParams({ view: nextView, day: dayId, area: areaFilter, category: categoryFilter }); if (query) params.set("q", query); if (nextView === "map") params.set("mode", mode); return `/trips/${trip.slug}/plan?${params}`; };
  const libraryLink = (area = areaFilter, category = categoryFilter) => { const params = new URLSearchParams({ view: "planning", day: activeDayId, area, category }); if (query) params.set("q", query); return `/trips/${trip.slug}/plan?${params}`; };

  const library = <><header className="panel-heading"><div><span>LIBRARY</span><h2>攻略素材</h2></div><form><input type="hidden" name="view" value="planning"/><input type="hidden" name="day" value={activeDayId}/><input type="hidden" name="area" value={areaFilter}/><input type="hidden" name="category" value={categoryFilter}/><input name="q" defaultValue={query} placeholder="搜索当前地域素材" aria-label="搜索攻略素材"/><button>搜索</button></form></header><nav className="recommendation-area-filters" aria-label="素材地域">{areaFilters.map(({ key, label }) => <a className={areaFilter === key ? "active" : ""} href={libraryLink(key, categoryFilter)} key={key}>{label}</a>)}</nav><nav className="recommendation-filters" aria-label="素材分类">{categoryFilters.map(({ key, label }) => <a className={categoryFilter === key ? "active" : ""} href={libraryLink(areaFilter, key)} key={key}>{label}</a>)}</nav><div className="recommendation-section-title"><b>{areaFilters.find(({ key }) => key === areaFilter)?.label} · {categoryFilters.find(({ key }) => key === categoryFilter)?.label}</b><span>{filteredRecommendations.length} 条</span></div><div className="recommendation-grid">{filteredRecommendations.map((recommendation) => { const added = days.map((day) => ({ day, count: recommendation.addedDays.filter((dayId) => dayId === day.id).length })).filter(({ count }) => count > 0); return <article className="recommendation-card" key={recommendation.id}>{recommendation.coverImageUrl ? <img src={recommendation.coverImageUrl} alt=""/> : <div className="recommendation-cover"><span>{recommendation.kind === "guide" ? "GUIDE" : recommendation.areaKey?.toUpperCase() || "PLACE"}</span><i/></div>}<div className="recommendation-card-body"><div className="recommendation-tags"><span>{recommendation.isCore ? "核心" : "收藏"}</span><span>{recommendation.kind === "guide" ? "攻略" : categoryLabels[recommendation.category]}</span><span>{recommendation.areaLabel}</span></div><h3>{recommendation.title}</h3>{(recommendation.estimatedDurationMinutes != null || recommendation.estimatedCostMinor != null) && <p>{recommendation.estimatedDurationMinutes != null ? `${recommendation.estimatedDurationMinutes} 分钟` : ""}{recommendation.estimatedCostMinor != null ? ` · ${money(recommendation.estimatedCostMinor)}` : ""}</p>}<p className="recommendation-state">{added.length ? `已加入 ${added.map(({ day, count }) => `${shortDate(day.date)}${count > 1 ? ` ×${count}` : ""}`).join(" · ")}` : "尚未加入正式行程"}{recommendation.locked ? " · 已锁定" : ""}</p><RecommendationAddControl slug={trip.slug} recommendationId={recommendation.id} days={dayLabels} defaultDayId={activeDayId} addedDayIds={recommendation.addedDays}/></div></article>; })}</div>{!filteredRecommendations.length && <div className="plan-empty">当前筛选下还没有攻略素材。</div>}<a className="view-all-materials" href={libraryLink(areaFilter, "all")}>查看当前地域全部素材 →</a></>;

  const itinerary = <><header className="panel-heading"><div><span>DAY PLAN</span><h2>{activeDay ? `${shortDate(activeDay.date)} · ${dayArea(activeDay)}` : "当天行程"}</h2></div></header>{workspace.presenceUnknown && <div className="presence-note"><b>成员在场信息待补充</b><span>{stageSummary} 只是阶段参与摘要，不代表任意时点实时人数。</span></div>}<div className="plan-timeline">{activeDay?.timeline.map((entry, index) => { const detail = entry.source === "itinerary" ? activeDay.items.find(({ item }) => item.id === entry.sourceId) : null; return <article key={`${entry.source}-${entry.sourceId}`} className={entry.source === "booking" ? "booking-entry" : "item-entry"}><div className="timeline-index">{entry.source === "booking" ? bookingIcon(bookings.find(({ booking }) => booking.id === entry.sourceId)?.booking.type || "") : String(index + 1).padStart(2, "0")}</div><div><div className="timeline-meta"><span>{entry.timeLocal || (entry.anchorKind === "start" ? "入住" : entry.anchorKind === "stay" ? "住宿中" : entry.anchorKind === "end" ? "退房" : "时间待定")}</span><span>{entry.source === "booking" ? "Booking Anchor" : detail?.item.lockedAt ? "已锁定" : "可调整"}</span></div><h3>{entry.title}</h3>{detail && <><p>{detail.item.placeId ? `地点：${detail.place?.name || "已绑定"}` : "地点待确认"}{detail.recommendationTitle ? ` · 来源：${detail.recommendationTitle}` : ""}</p><ItineraryItemControl slug={trip.slug} item={detail.item} days={dayLabels}/></>}{entry.source === "booking" && <p>已确认预订，不复制为行程事项。</p>}</div></article>; })}</div>{!activeDay?.items.length && <div className="plan-empty"><b>尚未安排</b><p>这一天还没有正式行程事项，可以从左侧攻略素材中添加。</p></div>}</>;

  return <main className="trip-plan-page"><header className="trip-console"><div className="console-title"><a href="/trips">← 攻略中心</a><span>TRIP CONSOLE</span><h1>{trip.title}</h1><p>{fullRange(trip.startDate, trip.endDate)} · {stageSummary}</p></div><div className="booking-console">{bookings.map(({ booking }) => <article key={booking.id}><b>{bookingIcon(booking.type)} {booking.title.replace("航班", "").replace("附近", "")}</b><span>{bookingStatus(booking.type)} · {bookingTime(booking)}</span><strong>{money(booking.totalAmountMinor)}</strong></article>)}{days.some((day) => day.items.some(({ item }) => item.itemType === "transit" && item.title.includes("上海"))) && !bookings.some(({ booking }) => booking.type === "train") && <article className="pending-booking"><b>🚄 上海→杭州</b><span>待确认</span><strong>—</strong></article>}</div></header><nav className="day-navigation" aria-label="选择日期">{days.map((day) => <a className={day.id === activeDayId ? "active" : ""} key={day.id} href={link(view, day.id)}><b>{shortDate(day.date)}</b><span>{dayArea(day)}</span></a>)}</nav><nav className="plan-view-tabs" aria-label="工作台视图"><a className={view === "planning" ? "active" : ""} href={link("planning")}>规划</a><a className={view === "map" ? "active" : ""} href={link("map")}>地图</a><a className={view === "budget" ? "active" : ""} href={link("budget")}>预算</a></nav>{view === "planning" && <PlanningPanels library={library} itinerary={itinerary}/>} {view === "map" && <section className="map-view"><header className="workspace-view-heading"><div><span>MAP</span><h2>{mapMode === "day" ? "当天路线" : "攻略地图"}</h2></div><nav><a className={mapMode === "day" ? "active" : ""} href={link("map", activeDayId, "day")}>当天路线</a><a className={mapMode === "library" ? "active" : ""} href={link("map", activeDayId, "library")}>攻略地图</a></nav></header><PlanMap slug={trip.slug} places={mapPlaces}/></section>}{view === "budget" && <section className="budget-view"><header className="workspace-view-heading"><div><span>BUDGET</span><h2>真实预算摘要</h2></div><strong>{money(confirmedTotal)}</strong></header><div className="confirmed-costs"><h3>已确认支出</h3>{bookings.map(({ booking }) => <article key={booking.id}><span>{bookingIcon(booking.type)} {booking.title}</span><b>{money(booking.totalAmountMinor)}</b></article>)}<article className="confirmed-total"><span>confirmed Booking 合计</span><b>{money(confirmedTotal)}</b></article></div><div className="allocation-cards"><h3>杭州酒店费用承担</h3>{costLines.map((line) => <article key={line.id}><header><div><b>{line.title}</b><span>{shortDate(line.serviceStartDate)}–{shortDate(line.serviceEndDate)}</span></div><strong>{money(line.amountMinor)}</strong></header><ul>{line.allocations.map(({ allocation, memberName }) => <li key={allocation.id}><span>{memberName}</span><b>{money(allocation.amountMinor)}</b></li>)}</ul></article>)}</div><p className="budget-disclaimer">以上是费用承担分配，不代表谁实际付款。未填写金额的攻略素材不计入预算。</p></section>}</main>;
}
